version: 2
description: Apply configuration changes to routers
parameters:
  targets:
    type: TargetSpec
  user:
    type: String
    description: The SSH username
  password:
    type: String
    description: The SSH password
steps:
  - name: gather_running_config
    task: bolt_project::ios_command
    targets: $targets
    parameters:
      host: $targets[0]['uri']
      user: $user
      password: $password
      command: show running-config

  - name: check_acl
    eval: |
      if ($gather_running_config['results'][0]['value']['stdout'] =~ /ip access-list standard TEST_ACL/ && 
          $gather_running_config['results'][0]['value']['stdout'] =~ /permit 192.168.0.0 0.0.255.255/) {
        return {'apply_acl': false}
      } else {
        return {'apply_acl': true}
      }

  - name: maybe_apply_acl
    if: $check_acl['apply_acl']
    then:
      - name: apply_acl
        task: bolt_project::ios_command
        targets: $targets
        parameters:
          host: $targets[0]['uri']
          user: $user
          password: $password
          command: |
            configure terminal
            ip access-list standard TEST_ACL
            permit 192.168.0.0 0.0.255.255
    else:
      - name: noop
        eval: "return {}"

return: "ACL applied to ${targets} if necessary"
