---
- name: Test Telnet Connection to Switch
  hosts: switches
  gather_facts: no
  tasks:
    - name: Run show version
      ios_command:
        commands:
          - show version
      register: output

    - name: Display output
      debug:
        var: output.stdout
