---
- name: Execute and Verify Commands on Cisco Device
  hosts: cisco_devices
  gather_facts: no

  tasks:
    - name: Show running configuration
      ios_command:
        commands: 
          - show running-config
      register: output

    - name: Display the running configuration
      debug:
        msg: "{{ output.stdout_lines }}"
