- name: Apply configuration change to routers
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather current running config
      ios_command:
        commands:
          - show running-config
      register: running_config

    # Comment out or remove this task to stop printing the running config
    # - name: Debug current running config
    #   debug:
    #     msg: "{{ running_config.stdout[0] }}"

    - name: Ensure ACL configuration is present
      ios_config:
        lines:
          - permit {{ ip_range }} {{ wildcard_mask }}
        parents: ip access-list standard {{ acl_name }}
      when: "'ip access-list standard {{ acl_name }}' not in running_config.stdout[0] or 'permit {{ ip_range }} {{ wildcard_mask }}' not in running_config.stdout[0]"
