---
- name: Apply configuration change to routers
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather current running config
      ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Ensure ACL configuration is present
      ios_config:
        lines:
          - permit {{ ip_range }} {{ wildcard_mask }}
        parents: ip access-list standard TEST_ACL
      when: 
        - "'ip access-list standard TEST_ACL' not in running_config.stdout[0]"
        - "'permit {{ ip_range }} {{ wildcard_mask }}' not in running_config.stdout[0]"
